version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: debezium/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: debezium/kafka
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
